# development:
#   access_key_id: AKIAJH7J6QIUKE5SM2KA
#   secret_access_key: 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
# 	bucket_name: converge-rails
# test:
#   access_key_id: AKIAJH7J6QIUKE5SM2KA
#   secret_access_key: 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
# 	bucket_name: converge-rails
# production:
#   access_key_id: AKIAJH7J6QIUKE5SM2KA
#   secret_access_key: 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
# 	bucket_name: converge-rails
# 	